In [1]:
!pip install numpy

In [2]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
print(arr2.shape)  # Returns (2,3) -> Rows x Columns
print(arr2.ndim)   # Number of dimensions
print(arr2.size)   # Total number of elements
print(arr2.dtype)  # Data type of elements

(2, 3)
2
6
int64


In [10]:
np.zeros((3,3))      # 3x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,2))       # 2x2 matrix of ones

array([[1., 1.],
       [1., 1.]])

In [12]:
np.eye(3)            # 3x3 Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.full((2,3), 5)    # 2x3 matrix filled with 5

array([[5, 5, 5],
       [5, 5, 5]])

In [5]:
np.arange(1, 10, 2)  # Array from 1 to 10 with step 2

array([1, 3, 5, 7, 9])

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)  # Matrix addition
print("---------")
print(A / B)  # Element-wise division
print("---------")
print(A * B)  # Element-wise multiplication
print("---------")
print(A - B)  # Matrix subtraction
print("---------")
print(A @ B)  # Matrix multiplication
print("---------")
print(A.T)    # Transpose of A

[[ 6  8]
 [10 12]]
---------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
---------
[[ 5 12]
 [21 32]]
---------
[[-4 -4]
 [-4 -4]]
---------
[[19 22]
 [43 50]]
---------
[[1 3]
 [2 4]]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[0])       # First row
print(arr[-1])      # Last row
print(arr[1:4])     # Rows from index 1 to 3
print(arr[:2, 1:])  # First 2 rows, columns from index 1 onward
print(arr[:, 1])    # Second column (all rows)


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1])    # Access element at index 1 -> 20
print(arr[1:4])  # Slice elements from index 1 to 3 -> [20, 30, 40]
print(arr[:3])   # First three elements
print(arr[-1])   # Last element